name: Daily Python Job

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v5

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar Chrome e ChromeDriver
        uses: browser-actions/setup-chrome@v2
        with:
          install-chromedriver: true

      - name: Verificar Chrome e ChromeDriver
        run: |
          google-chrome --version || chrome --version || chromium --version
          chromedriver --version

      - name: Rodar script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TV_USERNAME: ${{ secrets.TV_USERNAME }}
          TV_PASSWORD: ${{ secrets.TV_PASSWORD }}
        run: python projeto_hilo.py
